[package]
name = "poc-injector"
version = "0.1.0"
edition = "2021"

[dependencies]
lexopt = "0.3.0"
airborne-utils = { path = "../utils" }

[dependencies.windows-sys]
version = "0.52.0"
features = [
    "Win32_Foundation",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_ToolHelp",
]
